### ISSUE TITLE
How did you generate mask?

### ISSUE THREAD

**Issue by donghyukjung** [BingyaoHuang/SPAA#1]
Thanks for your awesome paper!

I have a one question, how did you generate mask?
In paper, you use the method which is suggested in [Fast separation of direct and global components of a scene using high frequency illumination]. I understand this method use a projector for project check pattern, but the projector is already the component of the scene. did you use two projectors?

**Comment by BingyaoHuang** [comment]
No, I use the same projector to project both shifted checkerboard patterns and the textured sampling images. Please refer to [DeProCams implementation ](https://github.com/BingyaoHuang/DeProCams/blob/main/src/python/trainNetwork.py#L41 )for more details.

**Comment by donghyukjung** [comment]
Thanks for your reply
But I can't find  'cam/raw/cb' in given DeProCams datasets. Where can I find it?

**Comment by BingyaoHuang** [comment]
Check `setups\camo_cmp\cam\raw\cb`.

**Comment by donghyukjung** [comment]
Thanks! I find it immediately after issue and I delete it. I'm sorry to that.
